on: pull_request

jobs:
  checkstyle_job:
    name: Checkstyle job
    runs-on: ubuntu-latest
    steps:
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.3.1
        with:
          github_token: ${{ github.token }}
