on: [pull_request, workflow_dispatch]

jobs:
  checkstyle_job:
    name: Checkstyle job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: 'error'
        checkstyle_config: 'src/main/resources/google_checks.xml'
        reporter: 'github-pr-review'
        tool_name: 'reviewdog'
